// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geek/04/configs"
	"geek/04/internal/biz"
	"geek/04/internal/data"
	"geek/04/internal/server"
	"geek/04/internal/service"
)

// Injectors from wire.go:

func initApp(config *configs.Config) (*userApp, error) {
	httpServer := server.NewHttpServer(config)
	db, err := data.NewDatabase(config)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(db)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	mainUserApp := newUserApp(httpServer, userService)
	return mainUserApp, nil
}
