// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geek/04/internal/biz"
	"geek/04/internal/data"
	"geek/04/internal/service"
)

// Injectors from wire.go:

func InitializeAllInstance() *service.UserService {
	userRepo := data.NewUserRepo()
	userBiz := biz.NewUserBiz(userRepo)
	userService := service.NewUserService(userBiz)
	return userService
}
